<?php

/**
 * @file
 * Provides pre-processors to format FAQ output properly.
 */

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function nir_faq_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if ($variables['elements']['#base_plugin_id'] == 'block_content') {
    $block = $variables['elements']['content']['#block_content'];
    if ($block->bundle() == 'nir_faq') {
      $display = $block->field_nir_faq_display_style->value;

      if ($display == 'accordion') {
        $suggestions[] = 'block__nir_faq_accordion';
      }
      else {
        $suggestions[] = 'block__nir_faq_list';
      }
    }
  }
}

 /**
  * Implements hook_preprocess_block().
  *
  * Adds pre-processing for faq block.
  */
function nir_faq_preprocess_block(&$variables) {
  if ($variables['elements']['#base_plugin_id'] == 'block_content') {
    $block = $variables['elements']['content']['#block_content'];
    if ($block->bundle() == 'nir_faq') {
      $variables['block_content'] = $block;
      $variables['categories'] = $variables['elements']['content']['field_nir_faq_categories'];
      $items = [];
      foreach ($variables['categories'] as $catKey => $category) {
        if (is_numeric($catKey)) {
          $items[$catKey]['field_nir_faq_category_name'] = $category['#field_collection_item']->field_nir_faq_category_name->value;
          $items[$catKey]['field_nir_faq_items'] = [];
          foreach ($category['#field_collection_item']->field_nir_faq_items as $key => $item) {
            $items[$catKey]['field_nir_faq_items'][$key]['field_nir_faq_item_id'] = $item->value;
            $field_nir_faq_items = \Drupal::entityManager()->getStorage('field_collection_item')->load($item->value);
            $items[$catKey]['field_nir_faq_items'][$key]['field_nir_faq_question'] = $field_nir_faq_items->field_nir_faq_question->value;
            $items[$catKey]['field_nir_faq_items'][$key]['field_nir_faq_answer'] = $field_nir_faq_items->field_nir_faq_answer->value;
            $items[$catKey]['field_nir_faq_items'][$key]['field_nir_faq_item_displayed'] = $field_nir_faq_items->field_nir_faq_item_displayed->value;
          }
        }
      }
      $variables['categories'] = $items;

    }
  }
}
